$(function(){
	$("#pic1").click(function(){
		$(this).css("background","#E4E4E4");
		$(window).attr('location','index.html');
	});
	$("#pic2").click(function(){
		$(this).css("background","#E4E4E4");
		$(window).attr('location','case.php');
	});
	$("#pic3").click(function(){
		$(this).css("background","#E4E4E4");
		$(window).attr('location','jfshop.php');
	});
	$("#pic4").click(function(){
		$(this).css("background","#E4E4E4");
		$(window).attr('location','my.php');
	});
});

